### ISSUE TITLE
Getting a status code of 500 on every request

### ISSUE THREAD

**Issue by Josh-E-S** [prestix-studio/cloudns_api#13]
Maybe I'm completely missing something, but anything I try to POST or GET I get a {'status_code': 500, 'success': False, 'payload': {}, 'error': 'Something went wrong.'}

`import cloudns_api

# USERNAME:
CLOUDNS_API_AUTH_ID='1234'
# PASSWORD:
CLOUDNS_API_AUTH_PASSWORD='123456'

response = cloudns_api.record.list(domain_name='domain.com')
print(response.json())
`

**Comment by Josh-Estrada** [comment]
`import cloudns_api

# USERNAME:
CLOUDNS_API_AUTH_ID='1234'
# PASSWORD:
CLOUDNS_API_AUTH_PASSWORD='123456'

response = cloudns_api.record.list(domain_name='domain.com')
print(response.json())`
