### ISSUE TITLE
lack of TLSA support

### ISSUE THREAD

**Issue by jap** [prestix-studio/cloudns_api#3]
I tried setting up TLSA records using this library, but that fails as there is no support for that currently. I'll try to whip up a patch.

**Comment by hbradleyiii** [comment]
Sounds good! Send a pull request when you get it.

**Comment by hbradleyiii** [comment]
@jap I threw together some code to add support for TLSA, but I am neither familiar enough with TLSA nor do I have any use cases to test to make sure this is working correctly. If you have a chance, can you test this and let me know if you run into any issues? Thanks.
