### ISSUE TITLE
"python setup.py egg_info" failed with error code 1 when trying to install the module

### ISSUE THREAD

**Issue by karaluh** [prestix-studio/cloudns_api#6]
**pip install cloudns_api** produces the following error

Collecting cloudns_api
  Using cached https://files.pythonhosted.org/packages/2b/f7/196036db70ce179ea137dd8e8b6c5f21bae133d9c67809dcd4b3c16f9c41/cloudns_api-0.9.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-DrQnrZ/cloudns-api/setup.py", line 13, in <module>
        from cloudns_api import __version__ as version
      File "cloudns_api/__init__.py", line 18, in <module>
        from . import api     # noqa: F401
      File "cloudns_api/api.py", line 316
        kwargs = {**response.payload, **kwargs}
                   ^
    SyntaxError: invalid syntax
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-DrQnrZ/cloudns-api/

**Comment by hbradleyiii** [comment]
Are you using python 2? This isn't compatible with Python 2.

**Comment by karaluh** [comment]
After switching to python 3 the module installed without issues. Thanks and sorry for the noise.

**Comment by hbradleyiii** [comment]
No big deal. I had actually never bothered testing it in Python 2. I released a new version that will give a clear message when trying to install in Python 2 that it will only work in Python 3. Thanks for letting me know about this issue!
