### ISSUE TITLE
LICENSE file is missing in released tar.gz

### ISSUE THREAD

**Issue by tigerfoot** [prestix-studio/cloudns_api#8]
Hi there, I'm trying to build an experimental package for openSUSE, and I've seen that LICENSE file is not included inside the released tar.gz (whl too?)
The major distribution needs to have explicit license bundled with any distributed software.

**Comment by hbradleyiii** [comment]
Are you looking in this release: https://github.com/prestix-studio/cloudns_api/releases/tag/v0.9.3? It's included there. As far as I'm aware, the tar.gz includes all of the files in the project at the particular commit.

**Comment by hbradleyiii** [comment]
So, I see that it isn't in the dist-info directory when running pip install. I made a change where it is now included in that file. This should fix the issue. Let me know if you have any more trouble.

**Comment by tigerfoot** [comment]
Sorry I didn't precise the source tar.gz normally used was the one published on pypi. So normally everything will be fixed for future version.
https://files.pythonhosted.org/packages/source/c/cloudns_api/cloudns_api-%{version}.tar.gz
